package pedal

var validNamedKeys = map[string]struct{}{
	// Editing / navigation
	"backspace": {},
	"delete":    {},
	"enter":     {},
	"tab":       {},
	"esc":       {},
	"escape":    {},
	"up":        {},
	"down":      {},
	"left":      {},
	"right":     {},
	"home":      {},
	"end":       {},
	"pageup":    {},
	"pagedown":  {},

	// Function keys
	"f1":  {},
	"f2":  {},
	"f3":  {},
	"f4":  {},
	"f5":  {},
	"f6":  {},
	"f7":  {},
	"f8":  {},
	"f9":  {},
	"f10": {},
	"f11": {},
	"f12": {},
	"f13": {},
	"f14": {},
	"f15": {},
	"f16": {},
	"f17": {},
	"f18": {},
	"f19": {},
	"f20": {},
	"f21": {},
	"f22": {},
	"f23": {},
	"f24": {},

	// Modifiers
	"cmd":         {},
	"lcmd":        {},
	"rcmd":        {},
	"alt":         {},
	"lalt":        {},
	"ralt":        {},
	"ctrl":        {},
	"lctrl":       {},
	"rctrl":       {},
	"control":     {},
	"shift":       {},
	"lshift":      {},
	"rshift":      {},
	"capslock":    {},
	"space":       {},
	"print":       {},
	"printscreen": {},
	"insert":      {},
	"menu":        {},

	// Media
	"audio_mute":     {},
	"audio_vol_down": {},
	"audio_vol_up":   {},
	"audio_play":     {},
	"audio_stop":     {},
	"audio_pause":    {},
	"audio_prev":     {},
	"audio_next":     {},
	"audio_rewind":   {},
	"audio_forward":  {},
	"audio_repeat":   {},
	"audio_random":   {},

	// Numpad
	"num0":      {},
	"num1":      {},
	"num2":      {},
	"num3":      {},
	"num4":      {},
	"num5":      {},
	"num6":      {},
	"num7":      {},
	"num8":      {},
	"num9":      {},
	"num_lock":  {},
	"num.":      {},
	"num+":      {},
	"num-":      {},
	"num*":      {},
	"num/":      {},
	"num_clear": {},
	"num_enter": {},
	"num_equal": {},

	// Brightness / lights (non-Windows)
	"lights_mon_up":     {},
	"lights_mon_down":   {},
	"lights_kbd_toggle": {},
	"lights_kbd_up":     {},
	"lights_kbd_down":   {},

	// All letters (regardless of capitalization) and digits are valid as well
	// handled in isValidKeys function
}
