name: Feature Request
description: Suggest a new feature or just a smaller improvement to make StepKeys better
title: "[FEATURE]: "
labels: [feature]
body:
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: "Short description: Why is this feature important to you? Why for others?"
      placeholder: "I request this feature because..."
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Specification
      description: An in-depth description of the requested feature. How should it work? How shouldn't it?
      placeholder: It should...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the criterias the feature must meet to be considered complete?
      placeholder: eg. StepKeys must react to X event with...
    validations:
      required: true